version: "3.8"

services:

  # -----------------------------
  # EUREKA SERVER
  # -----------------------------
  eureka:
    image: chirag1804/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - micro-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # -----------------------------
  # CONFIG SERVER
  # -----------------------------
  config:
    image: chirag1804/config-service:latest
    ports:
      - "8888:8888"
    networks:
      - micro-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # -----------------------------
  # POSTGRES DATABASE
  # -----------------------------
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: Microservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TIGER
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - micro-net
    deploy:
      replicas: 1

  # -----------------------------
  # API GATEWAY
  # -----------------------------
  gateway:
    image: chirag1804/gateway-service:latest
    ports:
      - "8088:8088"
    networks:
      - micro-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # -----------------------------
  # PRODUCT SERVICE
  # -----------------------------
  product:
    image: chirag1804/product-service:latest
    networks:
      - micro-net
    deploy:
      replicas: 2

  # -----------------------------
  # CART SERVICE
  # -----------------------------
  cart:
    image: chirag1804/cart-service:latest
    networks:
      - micro-net
    deploy:
      replicas: 2

  # -----------------------------
  # INVENTORY SERVICE
  # -----------------------------
  inventory:
    image: chirag1804/inventory-service:latest
    networks:
      - micro-net
    deploy:
      replicas: 2

  # -----------------------------
  # PRICING SERVICE
  # -----------------------------
  pricing:
    image: chirag1804/pricing-service:latest
    networks:
      - micro-net
    deploy:
      replicas: 2

  # -----------------------------
  # PRODUCT CATALOG SERVICE
  # -----------------------------
  catalog:
    image: chirag1804/catalog-service:latest
    networks:
      - micro-net
    deploy:
      replicas: 2

  # -----------------------------
  # RECOMMENDATION SERVICE
  # -----------------------------
  recommendation:
    image: chirag1804/recommendation-service:latest
    networks:
      - micro-net
    deploy:
      replicas: 2

# -----------------------------
# NETWORK
# -----------------------------
networks:
  micro-net:
    driver: overlay

# -----------------------------
# VOLUME
# -----------------------------
volumes:
  pgdata:
